admin_commande:
    resource: "@ECommerceECommerceBundle/Resources/config/routingBackEnd.yml"
    prefix:   /admin/commande

admin_media:
    resource: "@ECommerceECommerceBundle/Resources/config/routingBackEnd.yml"
    prefix:   /admin/media

admin_categorie:
    resource: "@ECommerceECommerceBundle/Resources/config/routingBackEnd.yml"
    prefix:   /admin/categorie

admin_produit:
    resource: "@ECommerceECommerceBundle/Resources/config/routingBackEnd.yml"
    prefix:   /admin/produit

front:
    resource: "@ECommerceECommerceBundle/Resources/config/routingFrontEnd.yml"
    prefix:   /
