e_commerce_list_produit:
    path:     /
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Produit:list }

e_commerce_list_produits_categorie:
    path:     /categorie/{slug}
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Produit:listByCategorie }

e_commerce_recherche_produit:
    path:     /recherche
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Produit:recherche }

e_commerce_read_produit:
    path:     /read/{slug}
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Produit:read }

e_commerce_panier:
    path:     /panier
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Panier:list }

e_commerce_panier_livraison:
    path:     /panier/livraison
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Panier:livraison }

e_commerce_panier_validation:
    path:     /panier/validation
    defaults: { _controller: ECommerceECommerceBundle:FrontEnd/Panier:validation }
