e_commerce_utilisateur:
    resource: "@ECommerceUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

e_commerce_ecommerce_user:
    resource: "@ECommerceUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

e_commerce_e_commerce:
    resource: "@ECommerceECommerceBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"