admin_categorie:
    path:     /
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:index" }

admin_categorie_show:
    path:     /{id}/show
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:show" }

admin_categorie_new:
    path:     /new
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:new" }

admin_categorie_create:
    path:     /create
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:create" }
    methods:  POST

admin_categorie_edit:
    path:     /{id}/edit
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:edit" }

admin_categorie_update:
    path:     /{id}/update
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:update" }
    methods:  [POST, PUT]

admin_categorie_delete:
    path:     /{id}/delete
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Categorie:delete" }
    methods:  [POST, DELETE]
