admin_media:
    path:     /
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:index" }

admin_media_show:
    path:     /{id}/show
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:show" }

admin_media_new:
    path:     /new
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:new" }

admin_media_create:
    path:     /create
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:create" }
    methods:  POST

admin_media_edit:
    path:     /{id}/edit
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:edit" }

admin_media_update:
    path:     /{id}/update
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:update" }
    methods:  [POST, PUT]

admin_media_delete:
    path:     /{id}/delete
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Media:delete" }
    methods:  [POST, DELETE]
