admin_produit:
    path:     /
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:index" }

admin_produit_show:
    path:     /{id}/show
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:show" }

admin_produit_new:
    path:     /new
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:new" }

admin_produit_create:
    path:     /create
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:create" }
    methods:  POST

admin_produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:edit" }

admin_produit_update:
    path:     /{id}/update
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:update" }
    methods:  [POST, PUT]

admin_produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "ECommerceECommerceBundle:BackEnd/Produit:delete" }
    methods:  [POST, DELETE]
